//! The hub's systemd unit text for each relayed host: the listener, its service, the command drop-in,
//! and apply's drop-in.

use super::*;

// ─── `sotd topology apply` (plan §C, §F step 5) ──────────────────────────

/// The `sot-relay-tunnel@<host>` unit name for a host's reverse tunnel.
pub fn tunnel_unit(host: &str) -> String {
    format!("sot-relay-tunnel@{host}")
}

/// Hosts the hub reverse-tunnels to: every listed host except the hub
/// itself and any `frontend` box (D8 — a frontend's own daemon is never
/// dialled, so nothing tunnels to it). Independent of `daemon`: D4 keeps
/// the lab servers `daemon = false` in 0.6 while they still carry a relay
/// tunnel (shell + relay + sampled). File order, like every other derived
/// list here.
pub fn tunnel_hosts(topo: &Topology) -> Vec<&str> {
    topo.hosts.iter().filter(|h| h.name != topo.hub && !h.frontend).map(|h| h.name.as_str()).collect()
}

/// The `sot-host-relay-<host>.socket` unit name for the hub's own socket
/// for a host: the listener a peer forwards to, whose per-connection
/// instance runs `sotd stdio-bridge` on that host.
///
/// The host sits in the unit's PREFIX rather than after an `@`, and that
/// is forced, not taste. A socket with `Accept=yes` instantiates
/// `<prefix>@<connection id>.service`, so a templated *socket*
/// (`sot-host-relay@<host>.socket`) hands its service the connection id
/// and never the host — systemd issue #19071, open against the systemd
/// the hub runs. A per-host prefix is the only spelling in which the
/// service that ssh's out knows which box it is ssh'ing to. Hence
/// [`relay_socket_unit`] / [`relay_service_unit`]: per-host unit text
/// written by `sotd topology apply`, instead of one hand-installed
/// template.
pub fn relay_unit(host: &str) -> String {
    format!("sot-host-relay-{host}.socket")
}

/// The per-connection service template [`relay_unit`]'s socket activates:
/// `<prefix>@.service`, one instance per accepted connection.
pub fn relay_service_unit_file(host: &str) -> String {
    format!("sot-host-relay-{host}@.service")
}

/// The first lines of every unit file `apply` writes: the file is the
/// hub's (a hand edit is lost at the next refresh), and where an override
/// does survive.
const GENERATED_UNIT_HEADER: &str = "\
# Generated by sotd on the hub: rewritten whenever its text differs from what
# the running sotd generates (at each daemon start, and by `sotd topology
# refresh`). Never edit it by hand. A per-host Environment= override belongs
# in a drop-in of its own beside the service. The command is the hub's: it is
# set last among this unit's own drop-ins, by zz-sot-relay-command.conf; any
# .conf in that directory sorting after it is retired by refresh. A drop-in in
# another systemd directory that overrides the command is reported by refresh,
# not fixed.
";

/// The hub's listener for `host` — the unit file [`relay_unit`] names.
/// Generated, like [`apply_dropin`], rather than shipped: every line of it
/// is derived, and the path is [`relay_socket_path`]'s, so the listener
/// and `sotd topology relay-sockets` cannot disagree about where a peer
/// forwards to.
pub fn relay_socket_unit(host: &str) -> String {
    format!(
        "{GENERATED_UNIT_HEADER}#
# One listener per enrolled host. A peer forwards its own dial port to this
# socket (`ssh -L <port>:<this path> <hub>`), and each accepted connection
# gets its own `sotd stdio-bridge` on the far box ({service}). The socket
# exists whether or not that box is up, so its presence is never a liveness
# claim — only a completed hello is.
[Unit]
Description=Ship of Tools cross-host relay socket for {host}

[Socket]
ListenStream={path}
Accept=yes
# A route into another box's daemon, so owner-only — the posture the daemon's
# own endpoints hold. /run/user/<uid> is already 0700; this is the belt to
# that brace.
SocketMode=0600

[Install]
WantedBy=sockets.target
",
        service = relay_service_unit_file(host),
        path = relay_socket_path(host).display(),
    )
}

/// The per-connection bridge to `host` — the unit file
/// [`relay_service_unit_file`] names.
pub fn relay_service_unit(host: &str) -> String {
    format!(
        "{GENERATED_UNIT_HEADER}#
# One instance per accepted connection on {socket}. `%i` here is the
# connection id systemd made up, not the host — a templated socket cannot
# pass its own instance to the service it activates (systemd #19071), which
# is why this unit's NAME carries the host.
[Unit]
Description=Ship of Tools relay bridge to {host} (connection %i)
# A per-connection instance is garbage once it ends, failed or not; the
# journal keeps the reason. systemd reads this key in [Unit] only.
CollectMode=inactive-or-failed

[Service]
# The accepted connection IS the bridge's stdin/stdout. `stdio-bridge` puts
# nothing else on stdout, so the far daemon's bytes arrive unmixed; ssh's own
# complaints go to the journal.
StandardInput=socket
StandardOutput=socket
StandardError=journal
# A drop-in overrides either of these without regenerating the unit: a box
# whose `sotd` is not on a non-interactive ssh PATH (give the full path), or
# an ssh alias that differs from the declared name. The command is set
# last, in {command} beside this file.
# No daemon-label override:
# `stdio-bridge` with no argument resolves THIS box's own label, never one
# carried over the wire, so on every Unix box in the fleet it is the same
# socket this unit used to name explicitly.
Environment=SOT_RELAY_TARGET={host}
Environment=SOT_RELAY_SOTD=sotd
",
        socket = relay_unit(host),
        command = RELAY_COMMAND_DROPIN,
    )
}

/// The name of [`relay_command_dropin`]'s file. systemd applies drop-ins by file-name byte order, so this sorts after every drop-in name sotd or its docs used (`local.conf`, `no-mux.conf`, `topology.conf`) and after `systemctl edit`'s `override.conf`. `refresh` retires any `.conf` in the hub's own unit directory that sorts after it.
pub const RELAY_COMMAND_DROPIN: &str = "zz-sot-relay-command.conf";

/// The bridge's command, in a drop-in of its own: it is applied after the unit and after the drop-ins of the hub's own unit directory that sort before it, so its empty `ExecStart=` clears whatever such a file set, however that file spells it. Nothing reads another drop-in.
fn relay_command_dropin() -> String {
    format!(
        "{GENERATED_UNIT_HEADER}#
# The bridge's command, set last among this directory's drop-ins that sort before this file's name.
# -T: no pty, so nothing rewrites the byte stream. BatchMode: never prompt —
# an unreachable box must fail at once rather than hang. The ServerAlive pair
# closes a wedged network in ~45s. The three Control options switch ssh
# connection sharing off even where ~/.ssh/config turns it on for this host
# (a command-line option wins over the config file): sharing hung every
# bridge on one Windows host.
[Service]
ExecStart=
ExecStart={RELAY_COMMAND_LINE}
"
    )
}

/// The bridge's command line, written once: the command drop-in renders it, and `refresh` checks that systemd's
/// one `ExecStart` record for the service is exactly it.
const RELAY_COMMAND_LINE: &str = "/usr/bin/ssh -T -o BatchMode=yes -o ServerAliveInterval=15 -o ServerAliveCountMax=3 -o ControlMaster=no -o ControlPath=none -o ControlPersist=no ${SOT_RELAY_TARGET} ${SOT_RELAY_SOTD} stdio-bridge";

/// [`RELAY_COMMAND_LINE`], for the checks outside this module.
pub fn relay_command_line() -> &'static str {
    RELAY_COMMAND_LINE
}

/// Every file the hub generates for `host`, as (path under `~/.config/systemd/user`, text): the listener, its per-connection service, and the service's command drop-in. `apply` writes them, `refresh` rewrites any whose text differs, and a disable removes them.
pub fn relay_files(host: &str) -> [(String, String); 3] {
    [
        (relay_unit(host), relay_socket_unit(host)),
        (relay_service_unit_file(host), relay_service_unit(host)),
        (format!("{}.d/{RELAY_COMMAND_DROPIN}", relay_service_unit_file(host)), relay_command_dropin()),
    ]
}

/// Hosts the hub serves a socket for: every [`dialable_hosts`] entry but
/// the hub itself, whose endpoint is its own session socket and needs no
/// relay. File order, like every other derived list here.
pub fn relay_hosts(topo: &Topology) -> Vec<&str> {
    dialable_hosts(topo).filter(|h| h.name != topo.hub).map(|h| h.name.as_str()).collect()
}

/// Refuse anywhere but the hub, naming it and the subcommand — these
/// derivations are the HUB'S (it enables/disables the hub's systemd units,
/// or prints paths in the hub's own runtime dir), and answering them
/// elsewhere would be a confident wrong answer rather than a refusal.
pub fn require_hub(topo: &Topology, self_host: &str, subcommand: &str) -> Result<(), String> {
    if self_host != topo.hub {
        return Err(format!(
            "this box (`{self_host}`) is not the hub (`{}`); run `sotd topology {subcommand}` there instead",
            topo.hub
        ));
    }
    Ok(())
}

/// One unit family's convergence: enable what's wanted and not yet
/// enabled, disable what's enabled and no longer wanted. HOST names, not
/// unit names — the caller owns the `@`-template spelling.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct UnitDiff {
    pub enable: Vec<String>,
    pub disable: Vec<String>,
}

impl UnitDiff {
    pub fn is_empty(&self) -> bool {
        self.enable.is_empty() && self.disable.is_empty()
    }
}

fn converge(want: &[&str], enabled_now: &[String]) -> UnitDiff {
    UnitDiff {
        enable: want.iter().filter(|h| !enabled_now.iter().any(|e| e == *h)).map(|h| h.to_string()).collect(),
        disable: enabled_now.iter().filter(|e| !want.contains(&e.as_str())).cloned().collect(),
    }
}

/// What `apply` does to the hub's TWO unit families: `sot-relay-tunnel@*`
/// (the comm relay's reverse tunnels, [`tunnel_hosts`]) and
/// `sot-host-relay-*.socket` (the hub's own socket per dialable host,
/// [`relay_hosts`]). Two lists because the two families answer different
/// questions — a `frontend` box carries no relay tunnel but is dialable,
/// and a `daemon = false` server is the reverse — so one list could not
/// serve both without lying about one of them.
///
/// Pure: each `*_enabled_now` is whatever the caller already queried from
/// `systemctl`, so this is testable against a fixture with no systemd, and
/// a second call with the wanted lists is a no-op by construction.
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ApplyPlan {
    pub tunnels: UnitDiff,
    pub relays: UnitDiff,
}

impl ApplyPlan {
    pub fn is_empty(&self) -> bool {
        self.tunnels.is_empty() && self.relays.is_empty()
    }
}

pub fn apply_plan(topo: &Topology, tunnels_enabled_now: &[String], relays_enabled_now: &[String]) -> ApplyPlan {
    ApplyPlan {
        tunnels: converge(&tunnel_hosts(topo), tunnels_enabled_now),
        relays: converge(&relay_hosts(topo), relays_enabled_now),
    }
}

/// The name apply's own drop-in owns inside an instance's `.service.d/`
/// — fixed, and the same in both unit families, so a hand-made drop-in
/// beside it under any other name is never touched by a re-apply.
pub const APPLY_DROPIN_FILE: &str = "topology.conf";

/// The `ConditionHost=` drop-in text for one instance of either family:
/// the shared home means the same `[host.*]` list — and the same
/// `~/.config/systemd/user` — is visible on every box that shares it, so
/// enabling an instance there would start it on all of them. This pins
/// execution to the box whose hostname is the hub (host names equal
/// `host_name()`, module doc, so a plain match is enough).
pub fn apply_dropin(hub: &str) -> String {
    format!(
        "# Generated by `sotd topology apply` — regenerated on every apply, do not edit by hand.\n[Unit]\nConditionHost={hub}\n"
    )
}

#[cfg(test)]
mod tests {
    use super::super::tests::V2;
    use super::*;

    const APPLY_FIXTURE: &str = r#"
hub = "hub"

[host.hub]
daemon = true

[host.remote-a]
daemon = true

[host.remote-b]

[host.fe]
daemon = true
frontend = true
"#;

    /// The comm relay's reverse tunnels are a separate concern from who is
    /// dialable, and this is what pins them apart: `fe` is dialable (it
    /// declares `daemon`) and still carries no tunnel, `remote-b` carries
    /// a tunnel and is not dialable at all.
    #[test]
    fn tunnel_hosts_excludes_hub_and_frontend() {
        let t = parse(APPLY_FIXTURE).unwrap();
        assert_eq!(tunnel_hosts(&t), vec!["remote-a", "remote-b"]);
        assert_eq!(relay_hosts(&t), vec!["remote-a", "fe"]);
        // gamma in V2 is daemon AND frontend: no tunnel, but dialable.
        let v2 = parse(V2).unwrap();
        assert_eq!(tunnel_hosts(&v2), vec!["beta"]);
        assert_eq!(relay_hosts(&v2), vec!["gamma"]);
    }

    #[test]
    fn require_hub_refuses_elsewhere() {
        let t = parse(APPLY_FIXTURE).unwrap();
        assert!(require_hub(&t, "hub", "apply").is_ok());
        let e = require_hub(&t, "remote-a", "relay-sockets").unwrap_err();
        assert!(e.contains("`remote-a`") && e.contains("`hub`") && e.contains("relay-sockets"), "{e}");
    }

    #[test]
    fn apply_plan_enables_disables_and_settles() {
        let t = parse(APPLY_FIXTURE).unwrap();
        // Nothing enabled yet: enable everything each family wants.
        let p = apply_plan(&t, &[], &[]);
        assert_eq!(p.tunnels.enable, vec!["remote-a", "remote-b"]);
        assert!(p.tunnels.disable.is_empty());
        // Exactly one relay per dialable non-hub host, and no other.
        assert_eq!(p.relays.enable, vec!["remote-a", "fe"]);
        assert!(p.relays.disable.is_empty());
        // A stale instance (no longer declared) alongside one still wanted,
        // in each family independently.
        let p = apply_plan(&t, &["remote-a".to_string(), "gone".to_string()], &["fe".to_string(), "remote-b".to_string()]);
        assert_eq!(p.tunnels.enable, vec!["remote-b"]);
        assert_eq!(p.tunnels.disable, vec!["gone"]);
        assert_eq!(p.relays.enable, vec!["remote-a"]);
        // `remote-b` carries a tunnel but declares no daemon: a relay for
        // it is exactly the kind of stale instance apply takes away.
        assert_eq!(p.relays.disable, vec!["remote-b"]);
        // Second run, now converged: a true no-op.
        let p = apply_plan(
            &t,
            &["remote-a".to_string(), "remote-b".to_string()],
            &["remote-a".to_string(), "fe".to_string()],
        );
        assert!(p.is_empty(), "{p:?}");
    }

    #[test]
    fn apply_dropin_text_is_exact() {
        assert_eq!(
            apply_dropin("hub"),
            "# Generated by `sotd topology apply` — regenerated on every apply, do not edit by hand.\n[Unit]\nConditionHost=hub\n"
        );
        assert_eq!(tunnel_unit("remote-a"), "sot-relay-tunnel@remote-a");
        assert_eq!(relay_unit("remote-a"), "sot-host-relay-remote-a.socket");
        assert_eq!(relay_service_unit_file("remote-a"), "sot-host-relay-remote-a@.service");
    }

    /// The four lines the route actually rides on. The host is in the unit
    /// NAME (systemd #19071 — see [`relay_unit`]), the listener is exactly
    /// the path `relay-sockets` prints, `Accept=yes` is what gives each
    /// connection its own bridge, and ssh's `%C` must reach ssh as `%C` and
    /// not be eaten as a systemd specifier.
    #[test]
    fn relay_units_carry_the_host_and_the_declared_path() {
        let sock = relay_socket_unit("remote-a");
        assert!(sock.contains(&format!("ListenStream={}\n", relay_socket_path("remote-a").display())), "{sock}");
        assert!(sock.contains("\nAccept=yes\n"), "{sock}");
        assert!(sock.contains("sot-host-relay-remote-a@.service"), "{sock}");

        let svc = relay_service_unit("remote-a");
        assert!(svc.contains("Environment=SOT_RELAY_TARGET=remote-a\n"), "{svc}");
        assert!(!svc.contains("SOT_RELAY_LABEL"), "{svc}");
        assert!(relay_command_dropin().contains(" stdio-bridge\n"));
        assert!(!svc.contains("KillMode"), "{svc}");
        assert!(svc.contains("\nStandardInput=socket\n") && svc.contains("\nStandardOutput=socket\n"), "{svc}");
    }

    #[test]
    fn relay_service_unit_collects_from_the_unit_section() {
        let svc = relay_service_unit("remote-a");
        let (unit, service, collect) = (svc.find("\n[Unit]\n"), svc.find("\n[Service]\n"), svc.find("\nCollectMode=inactive-or-failed\n"));
        assert!(unit < collect && collect < service, "CollectMode belongs in [Unit], systemd ignores it in [Service]:\n{svc}");
    }

    /// The generated ssh line, run through real `ssh -G` against the block an
    /// older ENROLLING-A-HOST.md told operators to put in the hub's
    /// ~/.ssh/config: sharing must read off however the config sets it.
    #[cfg(target_os = "linux")]
    #[test]
    fn relay_ssh_turns_multiplexing_off_over_an_ssh_config_that_turns_it_on() {
        const OLD_ADVICE: &str = "Host remote-a\n    ControlMaster auto\n    ControlPath ~/.ssh/cm-%C\n    ControlPersist 10m\n";
        let svc = relay_command_dropin();
        let exec = svc.lines().find_map(|l| l.strip_prefix("ExecStart=/usr/bin/ssh ")).expect("ExecStart runs /usr/bin/ssh");
        let opts: Vec<&str> = exec.split_whitespace().take_while(|t| *t != "${SOT_RELAY_TARGET}").collect();
        let dir = std::env::temp_dir().join(format!("sot-f3-sshg-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let cfg = dir.join("config");
        std::fs::write(&cfg, OLD_ADVICE).unwrap();
        let out = std::process::Command::new("ssh")
            .arg("-F").arg(&cfg).arg("-G").args(&opts).arg("remote-a")
            .output()
            .expect("the OpenSSH client `ssh` must be on PATH for this test");
        let _ = std::fs::remove_dir_all(&dir);
        let eff = String::from_utf8_lossy(&out.stdout);
        assert!(out.status.success(), "ssh -G failed: {}", String::from_utf8_lossy(&out.stderr));
        let has = |want: &str| eff.lines().any(|l| l == want);
        assert!(has("controlmaster false"), "opts {opts:?}\n{eff}");
        assert!(has("controlpersist no"), "opts {opts:?}\n{eff}");
        assert!(!eff.lines().any(|l| l.starts_with("controlpath ")), "opts {opts:?}\n{eff}");
    }

    /// Measured with systemd-analyze verify, systemd 249: drop-ins apply in byte order of file name.
    #[test]
    fn relay_command_is_set_once_and_last() {
        let [_, (svc_name, svc), (name, dropin)] = relay_files("remote-a");
        assert!(!svc.lines().any(|l| l.starts_with("ExecStart")), "{svc}");
        assert!(svc.contains(RELAY_COMMAND_DROPIN), "{svc}");
        assert_eq!(name, format!("{svc_name}.d/{RELAY_COMMAND_DROPIN}"));
        let set: Vec<&str> = dropin.lines().filter(|l| !l.is_empty() && !l.starts_with('#')).collect();
        assert!(set.len() == 3 && set[..2] == ["[Service]", "ExecStart="], "{set:?}");
        assert!(set[2].starts_with("ExecStart=/usr/bin/ssh ") && set[2].ends_with(" stdio-bridge"), "{set:?}");
        for older in ["local.conf", "no-mux.conf", "override.conf", APPLY_DROPIN_FILE] {
            assert!(older < RELAY_COMMAND_DROPIN, "{older}");
        }
    }
}
